repos:
  # General Hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # Golang
  - repo: https://github.com/TekWizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-fmt
      # - id: go-imports
      # - id: no-go-testing
      # - id: golangci-lint
      # - id: go-unit-tests

  # Licensing
  - repo: https://github.com/fsfe/reuse-tool
    rev: v5.0.2
    hooks:
      - id: reuse
        name: Add License Headers
        files: ".*.go"
        pass_filenames: true
        args:
          - annotate
          - --copyright
          - "Ioannis Torakis <john.torakis@gmail.com>"
          - --year
          - "2026"
          # https://github.com/spdx/license-list-data/blob/main/text/MIT.txt
          - --license
          - "GPL-3.0-only.txt"
          - --copyright-prefix
          - "string-c"
          - --template
          - gpl3

  # Markdown Documentation ToC
  - repo: https://codeberg.org/frnmst/md-toc
    # Release updates (ATOM) https://codeberg.org/frnmst/md-toc/tags.atom
    rev: 9.0.0
    hooks:
      - id: md-toc
        args:
          # Skip header
          - --skip-lines
          - "1"
          - --in-place
          - github
          - -l
          - "4"
